sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
before_install:
  - docker build . -t test
  - docker run test yarn test
script:
  - yarn cover
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
  - node_modules
